# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/srt32/hkpg
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - run: go vet ./...
      - run: go test -v -race ./...
